### ISSUE TITLE
OpenVR wrapper as separate artifact?

### ISSUE THREAD

**Issue by skalarproduktraum** [phr00t/jmonkeyengine-virtual-reality#10]
Hi @phr00t,

first, huge 👍  for your efforts in creating Java wrappers for OpenVR -- it's been a great help to me :)

Second, I think that it could be even more helpful for people, especially outside the jMonkeyEngine ecosystem, if the wrapper would be available as a separate Maven artifact, independent of jMonkeyEngine/jMonkeyVR. About in the same manner as @jherico's jovr. For that I took the liberty of factoring out the classes and OpenVR binaries from your repository into a separate one, at https://github.com/skalarproduktraum/scenery-openvr 

That package could also be extended with the OpenVR header files and a script to jnaerate the wrappers automatically. I'd also be happy to transfer the repo to you or work on it together - whatever works. This proposal is just intended to save you some work :)

Let me know what you think!

**Comment by phr00t** [comment]
Thank you!

This issue is virtually the same as my only other open issue here: https://github.com/phr00t/jMonkeyVR/issues/3 -- which is why I'm going to close this issue.

I think it is a good idea, I just don't have the time to do it myself. What time I do get to spend on jMonkeyVR is currently integrating OSVR native support. After that, I want to update my jMonkeyEngine build which is required for jMonkeyVR.

I appreciate you helping out & encourage others to do the same to make these extras come to fruition.
